### ISSUE TITLE
Condel.pm

### ISSUE THREAD

**Issue by pontikos** [vplagnol/pipelines#15]
readline() on closed filehandle SIFT at /cluster/project8/vyp/AdamLevine/software/ensembl/Plugins/Condel.pm line 136.

**Comment by APLevine** [comment]
See http://comments.gmane.org/gmane.science.biology.ensembl.devel/10238.
Fix condel.dir in /cluster/project8/vyp/AdamLevine/software/ensembl/Plugins/config/Condel/config/condel_SP.conf
to point to the correct directory.
