### ISSUE TITLE
supportFrame issue

### ISSUE THREAD

**Issue by vplagnol** [vplagnol/pipelines#16]
Not sure I understand this line in the WGS_pipeline.sh script
supportFrame=${projectID}/`basename $supportFrame`
Doesn't it override the user submitted supportFrame information?

**Comment by pontikos** [comment]
Yes you're right.  Initially the idea was to copy the provided supportFrame file into the projectID directory
`cp -f $supportFrame $projectID/` but i commented that out yesterday.
I will fix that.

**Comment by vplagnol** [comment]
yes good idea. So use that standard location indeed, but bring the cp command back. Makes sense to me.

**Comment by pontikos** [comment]
https://github.com/vplagnol/pipelines/commit/2c452f59f35bffdf50d5cb4da04e961f2fa4cb3f
