### ISSUE TITLE
copy license from novoalign

### ISSUE THREAD

**Issue by vplagnol** [vplagnol/pipelines#18]

**Comment by vplagnol** [comment]
See:
Command line argument ignored: -c option is only available in licensed versions. at '-c'

you need no copy novoalign.lic from my folder Niko. Otherwise it won't run.

**Comment by pontikos** [comment]
Changed to point back to your versions of the program.
Also added symlink to novoalign.lic in my dir.
https://github.com/vplagnol/pipelines/commit/b68022ca060eeb0c2ec8d6d1a230a883031cce97
