### ISSUE TITLE
naming issues

### ISSUE THREAD

**Issue by vplagnol** [vplagnol/pipelines#19]
So just to be clear jointgvcf should really be call Genotypegvcf or something like that. The name is not quite right

**Comment by pontikos** [comment]
Have you commited your fix @vplagnol ?  Otherwise I can do it?

**Comment by vplagnol** [comment]
Just ran a commit now. Hopefully that does the job.



On Thu, Jan 29, 2015 at 3:28 PM, Nikolas Pontikos <notifications@github.com>
wrote:

> Have you commited your fix @vplagnol <https://github.com/vplagnol> ?
> Otherwise I can do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vplagnol/pipelines/issues/19#issuecomment-72043386>.
>



-- 
Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
