### ISSUE TITLE
Creating scripts folder in align mode

### ISSUE THREAD

**Issue by vplagnol** [vplagnol/pipelines#29]

**Comment by vplagnol** [comment]
Getting the following error message:
/cluster/project8/vyp/vincent/Software/pipeline/WGS/WGS_pipeline.sh: line 715: Syrris_January2015/align/scripts/align.sh: No such file or directory

Looks like the scripts folder is not created?

**Comment by pontikos** [comment]
Where are you running this from?

**Comment by vplagnol** [comment]
cd /scratch2/vyp-scratch2/cardio_sequence_data/ARVC/
sh scripts/submission_January2015.sh

Now I created the scripts folder but it does not generate any job.
Not sure if I am doing something wrong or it's the pipeline that has a
broken bit?



On Mon, Feb 2, 2015 at 11:53 PM, Nikolas Pontikos <notifications@github.com>
wrote:

> Where are you running this from?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vplagnol/pipelines/issues/29#issuecomment-72564471>.
>



-- 
Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol

**Comment by pontikos** [comment]
it's the symlink to the support file which is broken

**Comment by vplagnol** [comment]
I think the issue is that it does not find the supportFrame, even though I
specified it as an argument.
Must be me, but what is the wrong step here?

On Mon, Feb 2, 2015 at 11:56 PM, Vincent Plagnol <vincent.plagnol@gmail.com>
wrote:

> cd /scratch2/vyp-scratch2/cardio_sequence_data/ARVC/
> sh scripts/submission_January2015.sh
>
> Now I created the scripts folder but it does not generate any job.
> Not sure if I am doing something wrong or it's the pipeline that has a
> broken bit?
>
>
>
> On Mon, Feb 2, 2015 at 11:53 PM, Nikolas Pontikos <
> notifications@github.com> wrote:
>
>> Where are you running this from?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vplagnol/pipelines/issues/29#issuecomment-72564471>.
>>
>
>
>
> --
> Vincent Plagnol
> University College London Genetics Institute
> Darwin building, office 210
> Gower Street, London, WC1E 6BT
> Cell: +44-(0)7946-546923
> Office: +44-(0) 2031-084002
> Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
>



-- 
Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol

**Comment by pontikos** [comment]
Try again but this time specify the fullpath:
```
/goon2/scratch2/vyp-scratch2/cardio_sequence_data/ARVC/support/January2015.tab
```

**Comment by vplagnol** [comment]
Yes I just figured this out, your support frame has to be a hard path right
now.
mmm... will fix now, but yes a bit unstable. I think it would be best to
copy the support file to the location rather than using a symlink.

On Tue, Feb 3, 2015 at 12:00 AM, Nikolas Pontikos <notifications@github.com>
wrote:

> Try again but this time specify the fullpath:
>
> /goon2/scratch2/vyp-scratch2/cardio_sequence_data/ARVC/support/January2015.tab
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vplagnol/pipelines/issues/29#issuecomment-72565389>.
>



-- 
Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol

**Comment by pontikos** [comment]
ok I will change that.
The way I usually work is that I have a project file containing the variables like so:
```
rmhanpo@pchuckle:~/IBDAJE/Macrogen]$ cat AJ_PROJECT
reference=1kg
projectID=AJ
supportFrame=/goon2/project99/IBDAJE_raw/Macrogen/AJ_samples.txt
extraID=Levine_Macrogen
```

**Comment by pontikos** [comment]
Ok done if it doesn't work please reopen the issue.
