### ISSUE TITLE
more non-set output dir

### ISSUE THREAD

**Issue by vplagnol** [vplagnol/pipelines#30]

**Comment by vplagnol** [comment]
Same issues as before
+ read code f1 f2
/cluster/project8/vyp/vincent/Software/pipeline/WGS/WGS_pipeline.sh: line 689: outputdir: unbound variable
++ wc -l
+ njobs=0
/cluster/project8/vyp/vincent/Software/pipeline/WGS/WGS_pipeline.sh: line 715: outputdir: unbound variable

It's in gvcf_unsplit. Can you add the same fix you added before please?

**Comment by pontikos** [comment]
Let me know if c6a9fe5e26ec74846d775a42a51eb95d3baffbbc fixes it otherwise can you please point me to your files and I will get it working for you?

**Comment by vplagnol** [comment]
Yes looks OK now.  Thanks.
I will need to move to per chromosome gvcf at some point, what I am doing
is wasting time a bit.

I will look at your input files but I think it is my job now. I will
prepare things by Monday I hope.
